language: php

php:
  - '7.1'

before_script:
  # Install librabbitmq-c
  - sh tests/bin/install_rabbitmq-c.sh v0.6.0
  # Install the AMQP dependency (using the alpha release for PHP 7 support)
  - echo "$HOME/rabbitmq-c" | pecl install amqp-1.7.0alpha2

  # Install Composer dependencies
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
