language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

before_script:
  - sh provision/install_rabbitmq-c.sh v0.6.0
  # Install the AMQP dependency (using the alpha release for PHP 7 support)
  - yes | pecl install amqp-1.7.0alpha2
  - composer install
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit
