language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - { php: 5.4, env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' }

before_script:
  # Install librabbitmq-c
  - sh tests/bin/install_rabbitmq-c.sh v0.6.0
  # Install the AMQP dependency (using the alpha release for PHP 7 support)
  - echo "$HOME/rabbitmq-c" | pecl install amqp-1.7.0alpha2

  # Install Composer dependencies
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
